apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediasoup-frontend
  namespace: mediasoup
  labels:
    app: mediasoup-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediasoup-frontend
  template:
    metadata:
      labels:
        app: mediasoup-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/YOUR_PROJECT_ID/frontend:latest  # Replace YOUR_PROJECT_ID
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "https://yourdomain.com/api"  # Replace with your domain
        - name: NEXT_PUBLIC_SOCKET_URL
          value: "https://yourdomain.com"  # Replace with your domain
        - name: NEXT_PUBLIC_TURN_SERVER_HOST
          value: "yourdomain.com"  # Replace with your domain
        - name: NEXT_PUBLIC_TURN_SERVER_PORT
          value: "3478"
        - name: NEXT_PUBLIC_TURN_USERNAME
          value: "mediasoup"
        - name: NEXT_PUBLIC_TURN_PASSWORD
          value: "mediasoup123"
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false